# Generated by Django 4.1.3 on 2022-11-11 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo_publicacao', models.TextField()),
                ('excerto_publicacao', models.TextField()),
                ('imagem_publicacao', models.ImageField(blank=True, null=True, upload_to='media/publicacao/%Y/%m/%d')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
