# Generated by Django 4.1.3 on 2022-11-11 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='excerto_publicacao',
        ),
    ]
