# Generated by Django 4.1.3 on 2022-11-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0002_remove_publicacao_excerto_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='descricao_publicacao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
